services:
  php:
    build:
      context: ./docker
    volumes:
      - .:/var/www/html

  composer:
    build:
      context: ./docker
    volumes:
      - .:/var/www/html
    entrypoint: ["composer"]
