<?php

/*
 * The referring hosts the `Source` and `Medium` dimensions name, written for
 * this package. A host is matched in full first, then with one label taken
 * off the front at a time, so `news.google.nl` finds `google.nl`. A `name.*`
 * rule matches that name under any top-level domain, so `google.*` finds
 * `google.co.uk`. Add or override hosts with `dimensions.sources`, and
 * `utm_source` spellings with `dimensions.source_aliases`.
 *
 * Mediums: `organic` for search engines, `social` for social networks and
 * chat apps, `email` for webmail, and `referral` for everything else.
 */

return [

    'hosts' => [

        // Search engines.
        'google.*' => ['Google', 'organic'],
        'com.google.android.googlequicksearchbox' => ['Google', 'organic'],
        'bing.com' => ['Bing', 'organic'],
        'cn.bing.com' => ['Bing', 'organic'],
        'duckduckgo.com' => ['DuckDuckGo', 'organic'],
        'search.yahoo.com' => ['Yahoo', 'organic'],
        'search.yahoo.co.jp' => ['Yahoo', 'organic'],
        'yandex.*' => ['Yandex', 'organic'],
        'ya.ru' => ['Yandex', 'organic'],
        'baidu.com' => ['Baidu', 'organic'],
        'ecosia.org' => ['Ecosia', 'organic'],
        'search.brave.com' => ['Brave Search', 'organic'],
        'startpage.com' => ['Startpage', 'organic'],
        'qwant.com' => ['Qwant', 'organic'],
        'kagi.com' => ['Kagi', 'organic'],
        'mojeek.com' => ['Mojeek', 'organic'],
        'search.naver.com' => ['Naver', 'organic'],
        'naver.com' => ['Naver', 'organic'],
        'search.daum.net' => ['Daum', 'organic'],
        'seznam.cz' => ['Seznam', 'organic'],
        'so.com' => ['360 Search', 'organic'],
        'sogou.com' => ['Sogou', 'organic'],
        'ask.com' => ['Ask', 'organic'],
        'search.aol.com' => ['AOL', 'organic'],
        'presearch.com' => ['Presearch', 'organic'],
        'yep.com' => ['Yep', 'organic'],
        'petalsearch.com' => ['Petal Search', 'organic'],
        'search.lycos.com' => ['Lycos', 'organic'],
        'metager.org' => ['MetaGer', 'organic'],
        'swisscows.com' => ['Swisscows', 'organic'],

        // AI assistants.
        'chatgpt.com' => ['ChatGPT', 'referral'],
        'chat.openai.com' => ['ChatGPT', 'referral'],
        'claude.ai' => ['Claude', 'referral'],
        'gemini.google.com' => ['Gemini', 'referral'],
        'perplexity.ai' => ['Perplexity', 'referral'],
        'copilot.microsoft.com' => ['Copilot', 'referral'],
        'chat.mistral.ai' => ['Le Chat', 'referral'],
        'you.com' => ['You.com', 'referral'],
        'phind.com' => ['Phind', 'referral'],
        'chat.deepseek.com' => ['DeepSeek', 'referral'],

        // Social networks and communities.
        'facebook.com' => ['Facebook', 'social'],
        'fb.com' => ['Facebook', 'social'],
        'fb.me' => ['Facebook', 'social'],
        'messenger.com' => ['Messenger', 'social'],
        'instagram.com' => ['Instagram', 'social'],
        'threads.net' => ['Threads', 'social'],
        'threads.com' => ['Threads', 'social'],
        'x.com' => ['X', 'social'],
        'twitter.com' => ['X', 'social'],
        't.co' => ['X', 'social'],
        'linkedin.com' => ['LinkedIn', 'social'],
        'lnkd.in' => ['LinkedIn', 'social'],
        'com.linkedin.android' => ['LinkedIn', 'social'],
        'reddit.com' => ['Reddit', 'social'],
        'redd.it' => ['Reddit', 'social'],
        'com.reddit.frontpage' => ['Reddit', 'social'],
        'pinterest.*' => ['Pinterest', 'social'],
        'pin.it' => ['Pinterest', 'social'],
        'youtube.com' => ['YouTube', 'social'],
        'youtu.be' => ['YouTube', 'social'],
        'tiktok.com' => ['TikTok', 'social'],
        'bsky.app' => ['Bluesky', 'social'],
        'mastodon.social' => ['Mastodon', 'social'],
        'mastodon.online' => ['Mastodon', 'social'],
        'mstdn.social' => ['Mastodon', 'social'],
        'tumblr.com' => ['Tumblr', 'social'],
        'quora.com' => ['Quora', 'social'],
        'discord.com' => ['Discord', 'social'],
        'discordapp.com' => ['Discord', 'social'],
        't.me' => ['Telegram', 'social'],
        'telegram.org' => ['Telegram', 'social'],
        'whatsapp.com' => ['WhatsApp', 'social'],
        'wa.me' => ['WhatsApp', 'social'],
        'snapchat.com' => ['Snapchat', 'social'],
        'slack.com' => ['Slack', 'social'],
        'com.slack' => ['Slack', 'social'],
        'teams.microsoft.com' => ['Microsoft Teams', 'social'],
        'line.me' => ['LINE', 'social'],
        'vk.com' => ['VK', 'social'],
        'ok.ru' => ['Odnoklassniki', 'social'],
        'weibo.com' => ['Weibo', 'social'],
        'xing.com' => ['XING', 'social'],
        'nextdoor.com' => ['Nextdoor', 'social'],
        'twitch.tv' => ['Twitch', 'social'],
        'vimeo.com' => ['Vimeo', 'social'],
        'flipboard.com' => ['Flipboard', 'social'],
        'medium.com' => ['Medium', 'social'],
        'dev.to' => ['DEV', 'social'],
        'hashnode.com' => ['Hashnode', 'social'],

        // Webmail.
        'mail.google.com' => ['Gmail', 'email'],
        'com.google.android.gm' => ['Gmail', 'email'],
        'outlook.live.com' => ['Outlook', 'email'],
        'outlook.office.com' => ['Outlook', 'email'],
        'outlook.office365.com' => ['Outlook', 'email'],
        'mail.yahoo.com' => ['Yahoo Mail', 'email'],
        'mail.yahoo.co.jp' => ['Yahoo Mail', 'email'],
        'mail.aol.com' => ['AOL Mail', 'email'],
        'mail.proton.me' => ['Proton Mail', 'email'],
        'mail.protonmail.com' => ['Proton Mail', 'email'],
        'icloud.com' => ['iCloud Mail', 'email'],
        'fastmail.com' => ['Fastmail', 'email'],
        'app.fastmail.com' => ['Fastmail', 'email'],
        'mail.zoho.com' => ['Zoho Mail', 'email'],
        'app.hey.com' => ['HEY', 'email'],
        'app.tuta.com' => ['Tuta', 'email'],
        'mail.tutanota.com' => ['Tuta', 'email'],
        'gmx.*' => ['GMX', 'email'],
        'web.de' => ['WEB.DE', 'email'],
        'mail.yandex.ru' => ['Yandex Mail', 'email'],
        'e.mail.ru' => ['Mail.ru', 'email'],
        'mail.qq.com' => ['QQ Mail', 'email'],
        'mail.163.com' => ['NetEase Mail', 'email'],
        'mail.naver.com' => ['Naver Mail', 'email'],
        'webmail.kpnmail.nl' => ['KPN Mail', 'email'],
        'mail.ziggo.nl' => ['Ziggo Mail', 'email'],
        'webmail.orange.fr' => ['Orange Mail', 'email'],
        'mail.libero.it' => ['Libero Mail', 'email'],
        'mail.seznam.cz' => ['Seznam Mail', 'email'],

        // News, aggregators and developer sites.
        'news.ycombinator.com' => ['Hacker News', 'referral'],
        'lobste.rs' => ['Lobsters', 'referral'],
        'producthunt.com' => ['Product Hunt', 'referral'],
        'news.google.com' => ['Google News', 'referral'],
        'news.yahoo.com' => ['Yahoo News', 'referral'],
        'msn.com' => ['MSN', 'referral'],
        'feedly.com' => ['Feedly', 'referral'],
        'inoreader.com' => ['Inoreader', 'referral'],
        'getpocket.com' => ['Pocket', 'referral'],
        'flipboard.app' => ['Flipboard', 'referral'],
        'substack.com' => ['Substack', 'referral'],
        'github.com' => ['GitHub', 'referral'],
        'gitlab.com' => ['GitLab', 'referral'],
        'stackoverflow.com' => ['Stack Overflow', 'referral'],
        'stackexchange.com' => ['Stack Exchange', 'referral'],
        'wikipedia.org' => ['Wikipedia', 'referral'],
        'laravel-news.com' => ['Laravel News', 'referral'],
        'laracasts.com' => ['Laracasts', 'referral'],
        'packagist.org' => ['Packagist', 'referral'],
        'npmjs.com' => ['npm', 'referral'],
        'indiehackers.com' => ['Indie Hackers', 'referral'],
        'slashdot.org' => ['Slashdot', 'referral'],
        'digg.com' => ['Digg', 'referral'],

    ],

    /*
     * `utm_source` and `ref` values that name a source above in another
     * spelling, lowercased.
     */
    'aliases' => [

        'google' => 'Google',
        'bing' => 'Bing',
        'duckduckgo' => 'DuckDuckGo',
        'ddg' => 'DuckDuckGo',
        'yahoo' => 'Yahoo',
        'facebook' => 'Facebook',
        'fb' => 'Facebook',
        'instagram' => 'Instagram',
        'ig' => 'Instagram',
        'threads' => 'Threads',
        'twitter' => 'X',
        'x' => 'X',
        'linkedin' => 'LinkedIn',
        'reddit' => 'Reddit',
        'pinterest' => 'Pinterest',
        'youtube' => 'YouTube',
        'tiktok' => 'TikTok',
        'bluesky' => 'Bluesky',
        'bsky' => 'Bluesky',
        'mastodon' => 'Mastodon',
        'discord' => 'Discord',
        'telegram' => 'Telegram',
        'whatsapp' => 'WhatsApp',
        'slack' => 'Slack',
        'hackernews' => 'Hacker News',
        'hacker_news' => 'Hacker News',
        'hn' => 'Hacker News',
        'producthunt' => 'Product Hunt',
        'product_hunt' => 'Product Hunt',
        'chatgpt' => 'ChatGPT',
        'openai' => 'ChatGPT',
        'perplexity' => 'Perplexity',
        'claude' => 'Claude',
        'gemini' => 'Gemini',
        'copilot' => 'Copilot',

    ],

];
